---
  - name: Setup Filebeat on webservers
    hosts: webservers
    become: true
    tasks:
            - name: Download Metricbeat
              command: curl -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb
            - name: Install Metricbeat
              command: dpkg -i metricbeat-7.4.0-amd64.deb
            - copy:
                      src: /etc/ansible/metricbeat-config.yml
                      dest: /etc/metricbeat/metricbeat.yml
            - name: Enable system
              command: metricbeat modules enable docker
            - name: metricbeat setup
              command: metricbeat setup
            - name: Start metricbeat
              command: service metricbeat start
            - name: enable metricbeat service
              systemd:
                      name: metricbeat
                      enabled: yes